package com.manualImpl;

/**
 * A simulation of Token stream.
 * generated by Lexer and Parser could read Token from the stream
 */
public interface TokenReader {
    /**
     * return next token and remove it from stream stream
     * return null if stream is empty
     */
    Token read();

    /**
     * return next token and not remove it from stream stream
     * return null if stream is empty
     */
    Token peek();

    /**
     * backtrace token stream and restore the original token
     */
    void unread();

    /**
     * return the current position of the token stream
     */
    int getIndex();

    /**
     * set the current position of the token stream
     */
    void setIndex(int index);
}
